#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。

[project]
name = "tinted-aviutl2"
version = "0.1.0"

[artifacts."tinted-aviutl2.aux2"]
enabled = true
destination = "Plugin/tinted-aviutl2.aux2"

[artifacts."tinted-aviutl2.aux2".profiles.debug]
build = ["rake generate", "cargo build"]
source = "target/debug/tinted_aviutl2.dll"
enabled = true

[artifacts."tinted-aviutl2.aux2".profiles.release]
build = ["rake generate", "cargo build --release"]
source = "target/release/tinted_aviutl2.dll"
enabled = true

[artifacts."English.aul2"]
enabled = false
source = "https://raw.githubusercontent.com/aviutl2/aviutl2_community_translation/refs/heads/main/locales/community_en.aul2"
destination = "Language/English.aul2"
profiles = { debug = { enabled = true } }

[artifacts."English.tinted-aviutl2.aul2"]
source = "./i18n/English.tinted-aviutl2.aul2"
destination = "Language/English.tinted-aviutl2.aul2"

[development]
aviutl2_version = "2.00beta32"

[release]
prebuild = ["cargo about generate ./about.hbs -o ./release/package.txt"]
package_template = "./release/package.txt"

[catalog]
id = "sevenc-nanashi.tinted-aviutl2"
name = "Tinted AviUtl2"
author = "Nanashi."
summary = "tinted-theming をAviUtl2で使うプラグイン。"
type = "common"
description = { type = "url", url = "https://raw.githubusercontent.com/sevenc-nanashi/tinted-aviutl2/main/README.md" }
download_source = { type = "github", owner = "sevenc-nanashi", repo = "tinted-aviutl2" }
homepage = "https://github.com/sevenc-nanashi/tinted-aviutl2"
license = { type = "MIT", template = false, text = { type = "file", path = "./LICENSE" } }
original_author = "Tinted Theming"
niconi_commons_id = "sm45904404"
tags = ["UI"]
