[tools]
"github:tinted-theming/tinted-builder-rust" = "latest"
"github:sevenc-nanashi/aviutl2-cli" = { version = "0.5.0-preview.2", bin = "au2.exe" }
"cargo:cargo-about" = "latest"
"cargo:cargo-edit" = "latest"
ruby = "latest"
