original:
  supported-systems: [base16]
  filename: "./intermediate/original/{{ scheme-system }}-{{ scheme-slug }}.style.conf"

rainbow:
  supported-systems: [base16]
  filename: "./intermediate/rainbow/{{ scheme-system }}-{{ scheme-slug }}.style.conf"

informations:
  supported-systems: [base16]
  filename: "src/themes/{{ scheme-system }}-{{ scheme-slug }}.json"

